-- Mirrors src/data/sample-data.ts (camelCase in TS, snake_case in Postgres).
create table if not exists public.houses (
  id bigint generated by default as identity primary key,
  house_id bigint not null unique,
  house_name text not null,
  owner_name text not null,
  location text not null,
  number_of_room integer not null,
  people_per_room integer not null,
  price_per_room numeric(10, 2) not null,
  rate numeric(3, 2) not null,
  phone_number text not null,
  created_at timestamptz not null default now()
);

-- Seed the sample data. Safe to run more than once.
insert into public.houses (
  house_id, house_name, owner_name, location, number_of_room,
  people_per_room, price_per_room, rate, phone_number
)
values
  (1, 'Sunrise Residence', 'Sok Dara', 'Phnom Penh', 12, 2, 250, 4.5, '012 345 678'),
  (2, 'Green Garden House', 'Chan Sopheap', 'Siem Reap', 8, 3, 180, 4.2, '097 234 567'),
  (3, 'Mekong View Residence', 'Lim Vannak', 'Phnom Penh', 15, 2, 320, 4.7, '010 456 789'),
  (4, 'Royal Garden Apartments', 'Keo Sreymom', 'Battambang', 10, 4, 200, 4.3, '088 567 890'),
  (5, 'Lotus Residence', 'Heng Rithy', 'Kampot', 6, 2, 150, 4.6, '096 678 901'),
  (6, 'Peaceful Home', 'Meas Bopha', 'Kandal', 9, 3, 170, 4.1, '015 789 012'),
  (7, 'City Star Residence', 'Touch Sokha', 'Phnom Penh', 20, 1, 400, 4.8, '011 890 123'),
  (8, 'Angkor Comfort House', 'Ly Chenda', 'Siem Reap', 7, 2, 220, 4.4, '092 901 234'),
  (9, 'Riverside Residence', 'Nget Visal', 'Kampong Cham', 11, 4, 190, 4.0, '078 012 345'),
  (10, 'Golden Home', 'Pich Sreyneang', 'Takhmao', 14, 3, 280, 4.6, '069 123 456')
on conflict (house_id) do nothing;

-- Read access for the publishable key client (anon role).
grant usage on schema public to anon, authenticated;
grant select on public.houses to anon, authenticated;

-- Row Level Security: anyone can read houses, no one can write.
alter table public.houses enable row level security;

drop policy if exists "Houses are publicly readable" on public.houses;
create policy "Houses are publicly readable" on public.houses
  for select
  to anon, authenticated
  using (true);