-- House owner listings: owners create, update and delete their own houses,
-- rooms and photos. Customers read published houses with an available room
-- through the house_listings view.
-- Requires the two earlier migrations. Safe to run more than once.

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- Owners and admins can manage listings (admins are granted in the SQL Editor).
create or replace function public.can_manage_listings()
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('owner', 'admin')
  );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- houses: owner, description, utility prices, publish flag
-- ---------------------------------------------------------------------------

alter table public.houses
  add column if not exists owner_id uuid default auth.uid()
    references public.profiles(id) on delete cascade,
  add column if not exists description text,
  add column if not exists water_price numeric(10, 2) check (water_price >= 0),
  add column if not exists electricity_price numeric(10, 2)
    check (electricity_price >= 0),
  add column if not exists is_published boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();

-- The sample houses have no owner_id and keep their own name, phone and
-- rating. New listings leave these empty: the owner's name and phone come
-- from their profile, and ratings are hidden for now.
alter table public.houses
  alter column house_id drop not null,
  alter column owner_name drop not null,
  alter column phone_number drop not null,
  alter column rate drop not null;

create index if not exists houses_owner_id_idx on public.houses (owner_id);

drop trigger if exists houses_set_updated_at on public.houses;
create trigger houses_set_updated_at
  before update on public.houses
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- rooms: floor and room number default to 1, so a small house is one room
-- ---------------------------------------------------------------------------

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  house_id bigint not null references public.houses(id) on delete cascade,
  floor_number integer not null default 1 check (floor_number >= 0),
  -- Free text: owners pick their own numbers (e.g. "8", "101", "A2").
  room_number text not null default '1'
    check (length(trim(room_number)) > 0),
  monthly_price numeric(10, 2) not null check (monthly_price >= 0),
  booking_fee numeric(10, 2) not null default 0 check (booking_fee >= 0),
  width_m numeric(6, 2) check (width_m > 0),
  length_m numeric(6, 2) check (length_m > 0),
  people_per_room integer not null default 1 check (people_per_room >= 1),
  -- Set by hand by the owner until there is a booking system.
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (house_id, floor_number, room_number)
);

create index if not exists rooms_house_id_idx on public.rooms (house_id);

drop trigger if exists rooms_set_updated_at on public.rooms;
create trigger rooms_set_updated_at
  before update on public.rooms
  for each row execute function public.set_updated_at();

-- Room changes count as editing the house ("edited at" on the listing).
create or replace function public.touch_house_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.houses
  set updated_at = now()
  where id = coalesce(new.house_id, old.house_id);
  return null;
end;
$$;

drop trigger if exists rooms_touch_house on public.rooms;
create trigger rooms_touch_house
  after insert or update or delete on public.rooms
  for each row execute function public.touch_house_updated_at();

-- Move the sample houses' room counts and prices into rooms, then drop the
-- columns: rooms available, starting price and capacity are now worked out
-- from the rooms table.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'houses'
      and column_name = 'number_of_room'
  ) then
    insert into public.rooms (
      house_id, floor_number, room_number, monthly_price, people_per_room
    )
    select h.id, 1, n::text, h.price_per_room, h.people_per_room
    from public.houses h
    cross join generate_series(1, h.number_of_room) as n
    where not exists (select 1 from public.rooms r where r.house_id = h.id);

    alter table public.houses
      drop column number_of_room,
      drop column people_per_room,
      drop column price_per_room;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- house_images: photos of the house (room_id null) or of one room
-- ---------------------------------------------------------------------------

create table if not exists public.house_images (
  id bigint generated by default as identity primary key,
  house_id bigint not null references public.houses(id) on delete cascade,
  room_id bigint references public.rooms(id) on delete cascade,
  -- Path inside the house-images bucket: <owner id>/<house id>/<file>.webp
  storage_path text not null unique,
  -- Order in the gallery; the first house photo is the cover.
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists house_images_house_id_idx
  on public.house_images (house_id);
create index if not exists house_images_room_id_idx
  on public.house_images (room_id);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

grant select on public.rooms, public.house_images to anon, authenticated;
grant insert, update, delete on public.rooms, public.house_images
  to authenticated;

alter table public.rooms enable row level security;
alter table public.house_images enable row level security;

-- houses: customers read through house_listings; the table itself shows
-- published houses, plus owners' own hidden ones.
drop policy if exists "Houses are publicly readable" on public.houses;
drop policy if exists "Published or own houses are readable" on public.houses;
create policy "Published or own houses are readable" on public.houses
  for select
  to anon, authenticated
  using (
    is_published
    or owner_id = (select auth.uid())
    or public.is_admin()
  );

drop policy if exists "Owners create their own houses" on public.houses;
create policy "Owners create their own houses" on public.houses
  for insert
  to authenticated
  with check (
    owner_id = (select auth.uid()) and public.can_manage_listings()
  );

drop policy if exists "Owners update their own houses" on public.houses;
create policy "Owners update their own houses" on public.houses
  for update
  to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists "Owners delete their own houses" on public.houses;
create policy "Owners delete their own houses" on public.houses
  for delete
  to authenticated
  using (owner_id = (select auth.uid()));

-- rooms and house_images follow their house: readable when the house is,
-- writable by the house's owner. The subqueries run with houses' RLS.
-- Columns are qualified with the table name because houses also has a
-- (legacy) house_id column, which an unqualified name would resolve to.
drop policy if exists "Rooms are readable with their house" on public.rooms;
create policy "Rooms are readable with their house" on public.rooms
  for select
  to anon, authenticated
  using (
    exists (select 1 from public.houses h where h.id = rooms.house_id)
  );

drop policy if exists "Owners manage rooms of their houses" on public.rooms;
create policy "Owners manage rooms of their houses" on public.rooms
  for all
  to authenticated
  using (
    public.is_admin() or exists (
      select 1 from public.houses h
      where h.id = rooms.house_id and h.owner_id = (select auth.uid())
    )
  )
  with check (
    public.is_admin() or exists (
      select 1 from public.houses h
      where h.id = rooms.house_id and h.owner_id = (select auth.uid())
    )
  );

drop policy if exists "Images are readable with their house"
  on public.house_images;
create policy "Images are readable with their house" on public.house_images
  for select
  to anon, authenticated
  using (
    exists (
      select 1 from public.houses h where h.id = house_images.house_id
    )
  );

drop policy if exists "Owners manage images of their houses"
  on public.house_images;
create policy "Owners manage images of their houses" on public.house_images
  for all
  to authenticated
  using (
    public.is_admin() or exists (
      select 1 from public.houses h
      where h.id = house_images.house_id and h.owner_id = (select auth.uid())
    )
  )
  with check (
    (
      public.is_admin() or exists (
        select 1 from public.houses h
        where h.id = house_images.house_id and h.owner_id = (select auth.uid())
      )
    )
    -- A room photo must belong to a room of the same house.
    and (
      room_id is null or exists (
        select 1 from public.rooms r
        where r.id = house_images.room_id and r.house_id = house_images.house_id
      )
    )
  );

-- ---------------------------------------------------------------------------
-- Storage: public bucket for listing photos
-- ---------------------------------------------------------------------------

-- Photos are resized and converted to WebP in the browser before upload;
-- the 5 MB limit and MIME list are a server-side backstop.
insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
values (
  'house-images', 'house-images', true, 5242880,
  array['image/webp', 'image/jpeg', 'image/png']
)
on conflict (id) do nothing;

-- Anyone can view photos through their public URL. Owners can only write to
-- their own folder: house-images/<their user id>/...
drop policy if exists "Owners upload house images" on storage.objects;
create policy "Owners upload house images" on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'house-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and public.can_manage_listings()
  );

drop policy if exists "Owners read own house images" on storage.objects;
create policy "Owners read own house images" on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'house-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Owners delete own house images" on storage.objects;
create policy "Owners delete own house images" on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'house-images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ---------------------------------------------------------------------------
-- house_listings: what customers see on the home page
-- ---------------------------------------------------------------------------

-- One row per published house that has at least one available room, so fully
-- occupied or hidden houses don't show. Prices and capacity only count
-- available rooms.
--
-- This view runs with its owner's rights (no security_invoker), so it can read
-- the owner's name and phone from profiles, which are otherwise private. It
-- exposes only those two profile fields. Supabase's Security Advisor flags
-- this as a "security definer view"; that is expected here.
create or replace view public.house_listings as
select
  h.id,
  h.house_name,
  h.location,
  coalesce(p.full_name, h.owner_name) as owner_name,
  coalesce(p.phone_number, h.phone_number) as phone_number,
  count(r.id)::integer as available_rooms,
  min(r.monthly_price) as price_from,
  max(r.people_per_room) as max_people_per_room,
  (
    select i.storage_path
    from public.house_images i
    where i.house_id = h.id and i.room_id is null
    order by i.position, i.id
    limit 1
  ) as cover_image_path,
  h.created_at
from public.houses h
join public.rooms r on r.house_id = h.id and r.is_available
left join public.profiles p on p.id = h.owner_id
where h.is_published
group by h.id, p.id;

grant select on public.house_listings to anon, authenticated;
